### ISSUE TITLE
Reproducibility

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#10]
Need and argument so that raw data cane be saved into a seperate set of files. These files can then be imported with figure and points overlayed to see the cliked data. New function can be built to import these files along with figures.

**Comment by joelpick** [comment]
Possibly by default produce an object of class metaDigitise (or something) with a certain structure that includes user input and results. Then have a data extract function to get a nice data frame out for further use. Can then make a nice print function that shows how many figures of what type etc

**Comment by joelpick** [comment]
replot functions needed, takes output and repots everything onto the figure

**Comment by joelpick** [comment]
Also plotting input axis coords, groups names etc

**Comment by joelpick** [comment]
all addressed in other issues
