### ISSUE TITLE
test different file types

### ISSUE THREAD

**Issue by joelpick** [daniel1noble/metaDigitise#12]

**Comment by daniel1noble** [comment]
What do you mean here @joelpick?

Also, just an FYI. Replying to issues via email adds them to the issue on Github. In case you didn’t know.

**Comment by joelpick** [comment]
png, jpeg, pdf etc. We could list here file types tried and whether they work?

**Comment by daniel1noble** [comment]
Good call!

**Comment by joelpick** [comment]
I think that `magick' should deal with pretty much everything, but best to check

**Comment by joelpick** [comment]
png, pdf, jpg and tiff all work
