### ISSUE TITLE
histograms

### ISSUE THREAD

**Issue by joelpick** [daniel1noble/metaDigitise#13]
function to get data from histograms would be useful. Click on beginning and end of bar? Extract as mean x of a bar * frequency (rounded to nearest integer). This should not bias the mean, but will probably slightly underestimate SD?

**Comment by joelpick** [comment]
function added - still need to work out optimal way of inputing data

**Comment by joelpick** [comment]
from simulations, it seem that extracting data this way gives very good estimates of mean and sd

**Comment by daniel1noble** [comment]
Nice! I had a look at this and it all seemed pretty sensible to me!

Danno
