### ISSUE TITLE
log axes

### ISSUE THREAD

**Issue by joelpick** [daniel1noble/metaDigitise#14]
what to do with log axes?

**Comment by joelpick** [comment]
could have user specify this before calibration - should be easy enough to correct for. 

Issues: 
- Different types of log transformation (ln, log10, log 2etc)
- More generally, points clicked at large data values could be quite biased - even a few pixels out at 10,000 courses a big difference compared to at 1

**Comment by joelpick** [comment]
can address this kind of problem

![iris_boxplot_log](https://user-images.githubusercontent.com/17319024/32419896-0be2a224-c2d6-11e7-8fe3-26f909c699da.png)

**Comment by daniel1noble** [comment]
@joelpick Implemented this
