### ISSUE TITLE
metaDigitise

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#26]
Need a prompt for group identity regardless of number of groups. Seems like if you specify one group that id of group is never asked. At least when applied to bulk_metaDigitise...

**Comment by joelpick** [comment]
Yes I deliberately implemented that yesterday! - why is group is needed for 1 group?

**Comment by joelpick** [comment]
So as it was redraw didn’t work when group id is NA (as when group N = 1), so it is now entered as “” when group N = 1. I initially removed the prompt for group name in this case because I thought it was redundant (can discuss this further)

**Comment by daniel1noble** [comment]
I think it is needed because then the user can still specify the treatment group name, which is beneficial instead of just having the figure ID. Just something to think about...

**Comment by joelpick** [comment]
I'll put it back in for now … :P

**Comment by joelpick** [comment]
done

**Comment by joelpick** [comment]
So I think we need to discuss this some more. When asked for number of groups, we could have it that if the user selects 0, then they are not prompted for group names, if they select 1 they are ? (I am just resolving an issue that is the user selects 0 groups, they then are asked for info for 2 groups, 1 and 0!)
