### ISSUE TITLE
Add summary() to bulk_digitise so that all plot types output the same data.

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#30]

**Comment by joelpick** [comment]
output from `summary.metaDigitise` is the same from every plot_type

**Comment by daniel1noble** [comment]
Yep! Thanks. I just need to add that in. sorry that wasn’t clear

**Comment by joelpick** [comment]
it was, just wanted to let you know that it was ready to go!!

**Comment by daniel1noble** [comment]
You’re a machine @joelpick!
