### ISSUE TITLE
Tests for interactive user functions?

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#32]
Anyone have ideas on how we can write tests for `metaDigitise` that involves automated clicking of  points, means and SE's from figures? We can simulate data easy, but going through the prompts in R console to test that functions are working correctly would be nice

**Comment by wcornwell** [comment]
`menu(choices, graphics = TRUE)

perhaps?

**Comment by joelpick** [comment]
@wcornwell 

Two things:
We have input like that (different function - `readline`, but its good to know about that one too!) - do you know how tests can be implemented for it when package building?

We also have points that a user interactively selects by clicking on the graphical interface (through the `locator` function), and we also have no idea how to implement tests for these

**Comment by wcornwell** [comment]
Interesting!  If this is going to eventually be a web app, then there is [this package](https://cran.r-project.org/web/packages/RSelenium/vignettes/shinytesting.html) for testing at that stage.

If it's not, then I imagine the best approach would be to re-factor the interactive stuff out of  `metaDigitise` and then have a switch that allows the user to either pass in the information OR use the interactive approach.  Then you could test everything except basically the `locator` and `readline` calls.

**Comment by joelpick** [comment]
looks like we can do this with `with_mock` https://krlmlr.github.io/mockr/
