### ISSUE TITLE
metaDigitise process new images

### ISSUE THREAD

**Issue by joelpick** [daniel1noble/metaDigitise#44]
with file named 'iris_scatter_png.png' got error
```
> dat <- metaDigitise("./")
Do you want to...

1: Process new images
2: Import existing data
3: Edit existing data

Selection: 1
Error in details$images[-done_figures] : 
  only 0's may be mixed with negative subscripts
```

**Comment by joelpick** [comment]
seems not to be file name related
```
> setwd("/Users/joelpick/Dropbox/0_postdoc/10_metaDigitise/docs/images")
> dat <- metaDigitise("./")
Do you want to...

1: Process new images
2: Import existing data
3: Edit existing data

Selection: 1
Error in details$images[-done_figures] : 
  only 0's may be mixed with negative subscripts
```

but import works ...

**Comment by joelpick** [comment]
seemed that there was a rogue file in the caldat folder that didn't match a image file - `./caldat/iris_scatter_murp` ?? Good to note - if there are extra files in the calmat folder that don't match those in the image folder, then error if thrown

**Comment by joelpick** [comment]
looks like there i still an issue with file that have e.g. `_png` in their title - this will be removed from the relevant calmat name, and so subsequently won't work

**Comment by joelpick** [comment]
similarly dir_details also find anything with '_png' in the title, so for example it finds "iris_png.txt"

**Comment by daniel1noble** [comment]
Yep, this is a tricky one for regular expressions. Probably safest not to have file extension within names.

**Comment by joelpick** [comment]
the problem is that covers a lot of possible things users might write in the middle of a filename ".[pjt][dnip][fpg]*" for example it would capture "_pig" and remove it

 I think already ".[pjt][dnip][fpg]*$" seems to somewhat limit this - will test further

**Comment by joelpick** [comment]
I _think_ `[.][pjt][dnip][fpg]*$` works well?  `.` on its own captured also text so `spng` in a name would be captured as well as `.png`. `[.]` seems to resolve this. `$` indicates the end

**Comment by daniel1noble** [comment]
Nice, lets go with that then. Probably no time today to test out, but looks like a sensible solution.

**Comment by joelpick** [comment]
I've pushed it - will try and test lots on combos today

**Comment by daniel1noble** [comment]
Fixed I think now
