### ISSUE TITLE
"getRawData" function?

### ISSUE THREAD

**Issue by wcornwell** [daniel1noble/metaDigitise#50]
Pretty cool!  Just went though and used this for an on-going project!  Pretty slick!

Only usability note was as I had to add some data to an existing dataset, I needed to get the data into an existing data structure (rather than a stand-alone project all with metaDigitise) so had to get the raw data out.  (This is probably pretty common as a lot of meta-analyses will be a mix of data from images and from already existing files?)

Anyway, I did figure it out thanks to the readme, but 

```{r}
data <- metaDigitise(dir = "~/example_figs/", summary = FALSE)
```
is not super intuitive.  For those of us who are bad/lazy about reading instructions, maybe could add a "getRawData" function?

**Comment by daniel1noble** [comment]
Will! Cool. Glad you like it and I was just thinking about such a function
the other day, so great timing! I will implement this. Should be super easy
to do.

Hope you're having fun in Japan!

––
Dr. Daniel Noble | ARC DECRA Fellow
Level 5 West, Biological Sciences Building (E26)
Ecology & Evolution Research Centre (E&ERC)
School of Biological, Earth and Environmental Sciences (BEES)
*The University of New South Wales*
Sydney, NSW 2052
AUSTRALIA

T : +61 430 290 053
E : daniel.noble@unsw.edu.au <daniel.noble@mq.edu.au>
W: www.nobledan.com
Github: https://github.com/daniel1noble

**Comment by joelpick** [comment]
How about instead of a new function, adding a question to the end asking if you want summary or processed data? this way it would work with the import options inside metaDigitise. Or do you think an additional function is helpful @wcornwell?

**Comment by wcornwell** [comment]
sure that would work.  Great work on this @joelpick.  it's going to be super useful!

**Comment by joelpick** [comment]
@wcornwell so we looked this, and it turns out that there is actually an existing function that imports the data, and without prompting the user for anything, so is a bit more useful for putting in larger scripts. it's called `import_metaDigitise` (we might rename it to be more in keeping with capitalisation vs underscores). It takes has a directory argument and a summary argument - so you would want `summary=FALSE` in this case
