### ISSUE TITLE
SE and SD calculation

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/metaDigitise#53]
Change things in the data summary. If SD is provided, back calculate SE and include in an SE column. If SE is provided or CI back-calculate to SE and SD.

**Comment by joelpick** [comment]
Is this necessary over what we currently have?

**Comment by daniel1noble** [comment]
Not entirely, but it can be. We have all the information to calculate both
in any case (well, when we have n) and some studies (one I am doing now)
have already started compiling with SE instead of SD, so (it's not a huge
problem as SD can be calculated back to SE), to enter that data you need to
do the calculation from SD back to SE. Not sure why they didn't just go SD,
but this may be a common occurrence. Of course, we can still just do this
on the entire data frame with a simple little function post digitising,
but, users will likely have to write a little function for this. Anyway, we
can think about it

–––
Dr. Daniel Noble | ARC DECRA Fellow
Level 5 West, Biological Sciences Building (E26)
Ecology & Evolution Research Centre (E&ERC)
School of Biological, Earth and Environmental Sciences (BEES)
*The University of New South Wales*
Sydney, NSW 2052
AUSTRALIA

T : +61 430 290 053
E : daniel.noble@unsw.edu.au <daniel.noble@mq.edu.au>
W: www.nobledan.com
Github: https://github.com/daniel1noble

**Comment by daniel1noble** [comment]
@joelpick closed this issue
