### ISSUE TITLE
adding a variable for "comments"

### ISSUE THREAD

**Issue by ASanchez-Tojar** [daniel1noble/metaDigitise#55]
Hi there,

I think it would be very useful to have the possibility of adding comments to each data extracted. For example, I was extracting data from mean&var plots where they reported +/- 2SD, option that is not implemented in the package. A column with comments would allow us to follow up on those hopefully uncommon cases requiring further editing later on.

Cheers,
Alfredo.

**Comment by daniel1noble** [comment]
Thanks @ASanchez-Tojar! I think this is a great idea. Will try and get on this ASAP

**Comment by joelpick** [comment]
Good suggestion.

Having a look at this now. So I have implemented the option to add for a comment for each figure. So it asks you at the end if you want to add a comment, and saves it. At the moment it doesn’t output it anywhere - where/how do you think it would be best to? In the summary? - same comment in each row of summary for each figure?

**Comment by ASanchez-Tojar** [comment]
I think same comment in each row should be fine!
Thanks a lot.
Alfredo.
