### ISSUE TITLE
same sample size for all groups

### ISSUE THREAD

**Issue by ASanchez-Tojar** [daniel1noble/metaDigitise#56]
Another suggestion: When extracting data from multiple groups of a single plot, it'd be cool if one could specify at once the same sample size for all groups instead of being asked for the sample size as many times as groups are to be added.
Cheers,
Alfredo.

**Comment by daniel1noble** [comment]
Another good one. Can probably just add a question in...will have a look

**Comment by joelpick** [comment]
Thanks for the suggestion :)

So I think this should be implemented - on the latest version on a new ‘development’ branch - Dan will know how to install this :D. It needs testing - I think the logic works in the code, but I haven’t tested it. It especially might break down in the edit mode.
