### ISSUE TITLE
Error when editing image

### ISSUE THREAD

**Issue by martinig** [daniel1noble/metaDigitise#61]
I keep getting this error message when I try to edit previously processed images.

```
Error in internal_digitise(object$image_file) : 
  argument "cex" is missing, with no default
```

Here is the full context. (Note that it happens for all the files and no matter what step I try to make the edit on). Shinichi tried to troubleshoot it a bit for me, but we haven't had much luck.

```
> data <- metaDigitise(dir = "~/Documents/Files/Post-docs/UNSW 2022-2024/Aim 1/Extracting data from figures/")

Do you want to...

1: Process new images
2: Import existing data
3: Edit existing data

Selection: 3

Choose how you want to edit files:

1: Cycle through images
2: Choose specific file to edit
3: Enter previously omitted sample sizes

Selection: 1

Edit file? y/n  
y

Edit rotation? If yes, then the whole extraction will be redone (y/n)  
y
Error in internal_digitise(object$image_file) : 
  argument "cex" is missing, with no default
```

**Comment by joelpick** [comment]
Hi April, sorry about this - I will look into it. Would you be able to upload the directory with the images and caldat folder (or just a few of them) or email them to me (joel.l.pick@gmail.com)?

**Comment by daniel1noble** [comment]
@joelpick Should have fixed this. Thanks! Closing now.
