### ISSUE TITLE
Error: rsession-utf8.exe: FailedToExecuteCommand

### ISSUE THREAD

**Issue by dylangomes** [daniel1noble/metaDigitise#62]
After running `metaDigitise(getwd())` and selecting `1: Process new images` I get another question: 

`Are all plot types Different or the Same? (d/s)`
If I select `d`, I get the following error:

```
Error: rsession-utf8.exe: FailedToExecuteCommand `"gs" -q -dQUIET -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 "-sDEVICE=pngalpha" -dTextAlphaBits=4 -dGraphicsAlphaBits=4 "-r72x72"  "-sOutputFile=C:/Users/dgome/AppData/Local/Temp/Rtmp6lPiYK/magick-IgA9cgK2McqJNasPMcvLXExK9cdxqCHK%d" "-fC:/Users/dgome/AppData/Local/Temp/Rtmp6lPiYK/magick-Sk5oAHvMe7PvH3RgspMMzpc6o-dhUvss" "-fC:/Users/dgome/AppData/Local/Temp/Rtmp6lPiYK/magick-QTOQkeB4Slyng7Y3Qsiql2he9tJ2QM7K"' (The system cannot find the file specified.
) @ error/delegate.c/ExternalDelegateCommand/494
```

If I select "s", then I get the question 

```
Please specify the plot_type as either:

 m: Mean and error
 b: Box plot
 s: Scatter plot 
 h: Histogram
```

Any of these selections lead to the same error as above. It seems that something is missing, but I just downloaded the package, following the vignette. Any ideas about what is going on here?

```
> sessionInfo()
R version 4.2.2 (2022-10-31 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19045)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8   
[3] LC_MONETARY=English_United States.utf8 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.utf8    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] metaDigitise_1.0.1

loaded via a namespace (and not attached):
[1] compiler_4.2.2 magrittr_2.0.3 magick_2.7.4   tools_4.2.2    Rcpp_1.0.8.3 
```

**Comment by dylangomes** [comment]
It appears that this error occurs if the WD is set to the root directory, but the code works fine if the WD is switched to the top-most folder with images in it. The vignette section "Setting up directory structures", suggests that this shouldn't be the case "This is useful because it expedites digitising figures as it prevents users from having to constantly specify the directories and / or paths where files are stored." So the error appears to be related to properly searching for images within subdirectories of the working directory.

**Comment by joelpick** [comment]
Hi Dylan,

Sorry for the delay getting to this, and thank for reporting the bug. We would always suggest creating a folder to hold the images and the calibration data, as this helps contain the project - I will update the vignette to make this explicit. Were there images in the root directory when you ran this? I don't get this error on a mac, so might be a windows issue. 

Cheers
Joel

**Comment by daniel1noble** [comment]
I'm not entirely sure what exactly is unclear in the vignette in relation to the error above and I can't reproduce this error so I'll close for now
