### ISSUE TITLE
Error after selecting points on scattergraph

### ISSUE THREAD

**Issue by gls21** [daniel1noble/metaDigitise#63]
Hello,

I am trying to extract values from a scatterplot (I have attached the original image below).
![37_Yoshioka_2020_fig_2](https://github.com/daniel1noble/metaDigitise/assets/91906620/ece0159b-7427-478b-bca8-503301e69d6d)

I've worked through the metaDigitise process up to the stage where it asks me to input the first group identifier, and then click the points I want to add. I select all the points for the first group, and press esc to finish. 

It then returns the following error:
Error in if (select_points$x < max(box_x) & select_points$y < max(box_y) &  :   argument is of length zero

I've noticed it's not putting the points where I clicked (see image below). This happened for the other graph I extracted data for, but it didn't turn out to affect the numbers extracted, and didn't return an error. 

![image](https://github.com/daniel1noble/metaDigitise/assets/91906620/d4d0f4b2-0015-44c3-951a-d19cfeafd610)

Any help on this would be greatly appreciated.

Thanks!
Grace

**Comment by joelpick** [comment]
Hi Grace,

Are you using rstudio? and if so what version?

Cheers
Joel

**Comment by gls21** [comment]
Hi Joel,

Yes I am using RStudio 
- "R version 4.2.2 (2022-10-31 ucrt) -- "Innocent and Trusting"
- "Spotted Wakerobin" Release (e7373ef8, 2022-09-06) for Windows"

Thanks for pointing me towards shinyDigitise, I will give this a go as well!

Thanks,
Grace

**Comment by joelpick** [comment]
We think it's a known rstudio bug with the locator function that unpins the metaDigitise extraction. If you could also try in standalone R that would be really helpful, or try updating rstudio (I realise that can be super annoying!).

**Comment by gls21** [comment]
Hi,

I can confirm that both standalone R and shinyDigitise both work so thank you for this!

(I did also try updating RStudio but this didn't fix the issue).

Many thanks,
Grace
